language: cpp
compiler: gcc
script:
    - cmake -DCMAKE_BUILD_TYPE=Debug test/ && make
    - ./unit/unit --gtest_filter='*.*'

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - g++-4.8

sudo: off
