language: cpp
compiler: gcc
script:
    - cmake -DCMAKE_BUILD_TYPE=Debug test/ && make
    - ctest

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - g++-4.8
        - cmake

sudo: false
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
