language: cpp
compiler: gcc
script:
    - cmake -DCMAKE_BUILD_TYPE=Debug test/ && make
    - ctest

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - g++-5
        - cmake

sudo: false
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
